apiVersion: v1
kind: Config
users:
- name: ctf
  user:
    tokenFile: /run/secrets/kubernetes.io/serviceaccount/token
clusters:
- name: ctf
  cluster:
    server: https://kubernetes.default.svc.cluster.local
    certificate-authority: /run/secrets/kubernetes.io/serviceaccount/ca.crt
contexts:
- name: ctf
  context:
    cluster: ctf
    user: ctf
    namespace: ctf
current-context: ctf
preferences: {}
